#!/bin/bash
# Script para tratar de realizar la sincronización del cliente puppet
# Colocar en /etc/network/if-up.d/ para que se ejecute al levantar el interfaz de red
# Desde AdministracionSI no colocamos el fichero directamente en /etc/network/if-up.d/. En su lugar se coloca sinc-puppet para evitar retardos en la activación de interfaces de red.
# Esteban M. Navas Martín
# Fecha última modificación: 07/07/2017
# Modificado por Administracionsi: 17/02/2017

export DEBIAN_FRONTEND=noninteractive
export VERSION=2.18
export PATH="${PATH:+$PATH:}/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

SCRIPT=`basename "$0"`

function print_version {
	echo "$SCRIPT $VERSION"
}

function print_help {
        echo "$SCRIPT $VERSION"
        echo "Automated sinc puppet client"
        echo ""
        echo "Usage: $0 [OPTIONS]"
        echo "Recognized options:"
        echo "  -h               display this help and exit"
        echo "  -v               display $SCRIPT version and exit"
        echo "  -f               force $SCRIPT on SPLAYLIMIT"
        echo "  -f now           force $SCRIPT now"
        echo "  -r               renew cert client"
        echo ""
}

function solveapterrors {

  idioma=$LC_ALL
  export LC_ALL=C

  apt-get check 1>/dev/null 2>/tmp/apterrors

  if [ -s /tmp/apterrors ]; then
     grep "Unmet dependencies. Try using -f." /tmp/apterrors && apt-get -yf install && dpkg --configure -a && apt-get -y autoremove
     grep "dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem." /tmp/apterrors && dpkg --configure -a && apt-get -yf install && apt-get -y autoremove
     grep -E 'Encountered a section with no Package: header|Problem with MergeList ' /tmp/apterrors && rm -rf /var/lib/apt/lists/
  fi

  export LC_ALL=$idioma
}

function dosync {
  if [ "$1" == "-f" ] && [ "$2" == "now" ]; then
     echo "Conexión con servidor de puppet. Sincronizando puppet....." | logger -s -t $0
     puppet agent --onetime --no-daemonize >/dev/null 2>&1
     if [ $? -eq "0" ]; then
        echo "Sistema PUPPET correcto" | logger -s -t $0
        exit 0
     fi
  else
     echo "Conexión con servidor de puppet." | logger -s -t $0
     echo "Esperando un tiempo máximo de $SPLAYLIMIT para sincronizar puppet....." | logger -s -t $0
     puppet agent --onetime --no-daemonize --splay --splaylimit $SPLAYLIMIT >/dev/null 2>&1
     if [ $? -eq "0" ]; then
        echo "Sistema PUPPET correcto" | logger -s -t $0
        exit 0
     fi
  fi
}

# No forzar la ejecución de sinc_puppet por defecto
FORCE=false

# Leer y procesar argumentos
while getopts ":f: rvh" opt
do
    case $opt in
        v ) print_version
	    exit 0
	    ;;
        h ) print_help
 	    exit 0
	    ;;
        f)  force="-f"
            FORCE=true
            now=$OPTARG
            ;;
        r)  renew="-r"
            ;;
        \? ) echo "Opcion invalida -$OPTARG"
             exit 1
	     ;;
        : )  force="-f"
	     now=""
    esac
done
shift $((OPTIND-1))

# Mostrar ayuda si un caracter no deseado es introducido##
if [ -n "$1" ]; then
    print_help
fi

# Matamos procesos detenidos
stopped_processes=$(ps auwx | awk 'NR>1 && $8 ~ "T" {print $2}')
if [ "$stopped_processes" ]; then kill -9 $stopped_processes; fi

#Definimos fichero de lock
lockfile=/tmp/sincpuppet

# Matamos todos los procesos de sinc_puppet excepto el último que se haya
sinc_puppet_processes=$(pgrep -c sinc_puppet)
if [ "$sinc_puppet_processes" -gt "1" ]; then
        kill -9 $(ps -ef|grep "sinc_puppet"|grep -v grep| awk '{print $2}' |grep -v $$) 2>/dev/null
	#Si matamos con kill -9 todos los procesos sinc_puppet debemos borrar fichero de lock porque sino el proceso actual muere. 
        lockfile-remove $lockfile
fi

# Nos aseguramos de que sólo exista una instancia de sinc_puppet corriendo
# Eliminar fichero de bloqueo al salir
trap "lockfile-remove $lockfile; exit" INT TERM EXIT

lockfile-check $lockfile
if [ $? -eq 0 ] ; then
    # Si existe el fichero de bloqueo
    # echo >&2 "lock not acquired, giving up: $lockfile"
    exit 1
else
    # Si no existe el fichero de bloqueo
    lockfile-create $lockfile         # Creamos el fichero de bloqueo
    # echo "lock acquired: $lockfile"
fi

LOCALES="es_ES.UTF-8"

# Controlamos la ejecución manual o automática de sinc_puppet
ENABLE=yes
[ -r /etc/default/sincpuppet ] && . /etc/default/sincpuppet
$FORCE && ENABLE=yes

if [ "$ENABLE" == "no" ] || [ ! "$ENABLE" ]; then
  echo " * [info]: La aplicación 'sinc_puppet' está desactivada en /etc/default/sincpuppet."
  echo "           Para activarla poner el valor ENABLE=yes."
  exit 0
fi

# Establecemos los locales por defecto
export LANG=$LOCALES
export LANGUAGE="es_ES:es:en"
export LC_ALL=$LOCALES

# Número máximo de segundos sin sincronizar con el servidor puppet
MAXTIME=`expr $INTERVAL \* 3600`

# Calculamos la diferencia
uno=$(stat -c %Y  /var/log/syslog)
dos=$(stat -c %Y /var/lib/puppet/state/state.yaml)
dife=$((uno-dos))
dife2=0

if [ -f /var/lib/puppet/state/agent_catalog_run.lock ]; then
   tres=$(stat -c %Y /var/lib/puppet/state/agent_catalog_run.lock)
   dife2=$((uno-tres))
fi

if [ $dife2 -gt $MAXTIME ]; then
   rm -f /var/lib/puppet/state/agent_catalog_run.lock
fi

solveapterrors

echo "La última sincronización con PUPPET fue hace: "$(($dife / 3600)) "horas" | logger -s -t $0
echo "Intervalo de sincronización con PUPPET: $INTERVAL horas" | logger -s -t $0
echo

# Salimos si no se ha alcanzado el tiempo máximo sin sincronizar con PUPPET o no se ha forzado la ejecución
if [ $dife -lt $MAXTIME ] || [ $# -eq 1 ] && [ "$force" != "-f" ] || [ $# -eq 1 ] && [ "$renew" != "-r" ]; then exit 0; fi

ping -c 1 $PING_SERVER >/dev/null 2>&1
ERROR=$?
MAX=0

until [ $ERROR -eq "0" ] || [ $MAX -eq $PING_TRIES ]; do
 echo "Falló Ping al servidor Puppet. Nuevo intento en $PING_INTERVAL segundos....." | logger -s -t $0
 MAX=`expr $MAX + 1`
 sleep $PING_INTERVAL
 ping -c 1 $PING_SERVER >/dev/null 2>&1
 ERROR=$?
done

if [ $MAX -eq $PING_TRIES ]; then
 echo "Imposible contactar con el servidor....." | logger -s -t $0
 exit $MAX
fi

# Activamos puppet, por si estuviera desactivado
puppet agent --enable

if [ "$renew" == "-r" ]; then
   uuid=$(/usr/bin/uuidgen -t) && sed -i "s/certname=.*/certname=$uuid/" /usr/share/linex-ubuntu-puppet/puppet.conf
   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;
   dosync $force $now
fi


# Obtenemos el uuid del fichero puppet.conf
uuid=$(sed -n 's|certname=\(.*\)|\1|p' /usr/share/linex-ubuntu-puppet/puppet.conf)

# Si no existe el certificado del cliente, ejecutamos puppet tratando de recibir un certificado
if [ -z "$uuid" ]; then
   uuid=$(/usr/bin/uuidgen -t) && sed -i "/server=puppetinstituto/a certname=$uuid" /usr/share/linex-ubuntu-puppet/puppet.conf
   echo "Se ha generado un nuevo uuid para este host: $uuid" | logger -s -t $0
   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;

   dosync $force $now
fi

test -f /var/lib/puppet/ssl/certs/$uuid.pem
if [ $? -eq "0" ]; then

   dosync $force $now

   #Si existe el certificado uuid y no se consigue sincronizar. Se sincroniza la hora, se genera un nuevo uuid y se borran todos los certificados dentro de /var/lib/puppet/ssl
   ntpdate -u servidor 2>/dev/null
   uuid=$(/usr/bin/uuidgen -t) && sed -i "s/certname=.*/certname=$uuid/" /usr/share/linex-ubuntu-puppet/puppet.conf
   find /var/lib/puppet/ssl/ -type f -name *.pem -exec rm -f {} \;

   dosync $force $now

else
   [ -f /var/lib/puppet/state/puppetdlock ] && rm -f /var/lib/puppet/state/puppetdlock
   uuid=$(/usr/bin/uuidgen -t) && sed -i "s/certname=.*/certname=$uuid/" /usr/share/linex-ubuntu-puppet/puppet.conf
   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name $uuid.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;

   dosync $force $now
fi
