#!/bin/bash
### BEGIN INIT INFO
# Provides: sincpuppet
# Required-Start: $local_fs $network
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Daemon to synchronize puppet
# Description: daemon to synchronize puppet.
### END INIT INFO
# When the machine has unavailable network, nslcd slow down everything trying to take ldap info.
# This daemon try to recognize that unavailability and stop nslcd daemon until network is available again.

SINCPUPPET_BIN=/usr/sbin/sinc_puppet
SINCPUPPET_DESC="Daemon to synchronize puppet"

[ -x "$SINCPUPPET_BIN" ] || exit 0

. /lib/lsb/init-functions


start() {
 # set up state directory

  log_daemon_msg "Starting $SINCPUPPET_DESC" "SincPuppet"
  $SINCPUPPET_BIN &
  log_end_msg $?

}

stop() {
  log_daemon_msg "Stopping $SINCPUPPET_DESC" "SincPuppet"
  killall sinc_puppet
  log_end_msg $?

}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
esac


exit 0
