#!/bin/bash
set -e

mkdir -p /etc/pkgsync
touch /etc/pkgsync/mayhave
touch /etc/pkgsync/maynothave

invoke-rc.d puppet stop
update-rc.d -f puppet remove
update-rc.d -f sincpuppet remove

productname=`facter productname`
tipo=`facter tipo`

if [ -z $tipo ]; then
   case $productname in
      "HP ProDesk 600 G2 SFF") echo 'tipo=infolab' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "HP ProDesk 600 G1 SFF") echo 'tipo=siatic' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "HP x360 310 G2 PC") echo 'tipo=notebookHP' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "HP ProBook 4510s") echo 'tipo=HP-ProBook' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "P5Q DELUXE") echo 'tipo=Telefonica' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "8317KLG"|"8317KHG") echo 'tipo=ibm' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "8317KLG"|"TravelMate 5735Z") echo 'tipo=Travelmate' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "G41MT-S2") echo 'tipo=workstation' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "AO532h") echo 'tipo=notebookACER' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "N148P") echo 'tipo=notebookXTREM' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      "To be filled by O.E.M.") echo 'tipo=notebookAPD' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
      *) echo 'tipo=otros' >> /usr/share/linex-ubuntu-puppet/escuela2.0
      ;;
   esac
fi

[ -x /bin/systemctl ] &&  systemctl disable puppet.service

/usr/sbin/sinc_puppet &

exit 0
